#!/bin/bash

DATASETID=$1

#DATASETID="vXK2IApyj6g"
CREDENTIALS="test:Test1234"
BASE="https://rwanda/rwanda"

#Query fragments
CATEGORIES="categories\[displayName,categoryOptions\[displayName\]\]\]"
CATCOMBO="categoryCombo\[id\,categoryOptionCombos\[name,id,categoryOptions\[name,categories\[name\]\]\]\]"
DATAELEMENT="dataElement\[id,displayName,valueType,$CATCOMBO\]"

QUERY="fields=id,code,displayName,version,periodType,dataSetElements\[$DATAELEMENT,$CATCOMBO\]"

# fire away ...
curl -k -u $CREDENTIALS "$BASE/api/dataSets/$DATASETID.xml?$QUERY" 

