#!/bin/bash

CREDENTIALS='admin:district'
BASE='https://play.dhis2.org/dev'

# get all the dxf datasets from demo server
DATASETS=$(curl -s -u $CREDENTIALS "$BASE/api/dataSets.xml" 2>/dev/null|xpath -e '//@id' 2>/dev/null |sed 's/id=\"\(.*\)\"/\1/');

for ds in $DATASETS
do 
   echo "Fetching $ds"
   ./getDataSet $ds > ../dxf/dxf_$ds.xml; 
done

